### ISSUE TITLE
Primera Pregunta

### ISSUE THREAD

**Issue by JuanVargas** [camachojua/diplomado-ia#1]
Esta es una pregunta para comenzar la interaccin del diplomado de IA de la UNAM

**Comment by camachojua** [comment]
¡Excelente! :heart:

**Comment by EternalMark** [comment]
De acuerdo

**Comment by HugoDvega56** [comment]
Hola, un gusto participar en este diplomado

**Comment by Rikkonen** [comment]
Hola, espero aprender mucho
