### ISSUE TITLE
Ayuda para importar gowa

### ISSUE THREAD

**Issue by ffmorales** [camachojua/diplomado-ia#20]
Descomprimí gowa.zip e intenté correr el archivo: .../gowa/cmd/gowamain.go

Sin embargo tengo el siguiente error:

Build Error: go build -o /Users/fau/Documents/Code/DiplomadoIA/Git/diplomado-ia/go/src/gowa/cmd/__debug_bin2026629902 -gcflags all=-N -l .
gowamain.go:5:2: cannot find package "gowa/lib" in any of:
	/usr/local/go/src/gowa/lib (from $GOROOT)
	/Users/fau/go/src/gowa/lib (from $GOPATH) (exit status 1)

Creé el path de src/gowa en /Users/fau/go/
y luego copie y pegue allí el lib del programa.

Sin embargo ahora tengo problemas en las dependencias:

- github.com/go-sql-driver/mysql
- github.com/gorilla/sessions
- mkcog/mkcog/lib

Por el error:
Build Error: go build -o /Users/fau/Documents/Code/DiplomadoIA/Git/diplomado-ia/go/src/gowa/cmd/__debug_bin1311208010 -gcflags all=-N -l .
/Users/fau/go/src/gowa/lib/sqlQuery.go:10:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/usr/local/go/src/github.com/go-sql-driver/mysql (from $GOROOT)
	/Users/fau/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
/Users/fau/go/src/gowa/lib/sessions.go:7:2: cannot find package "github.com/gorilla/sessions" in any of:
	/usr/local/go/src/github.com/gorilla/sessions (from $GOROOT)
	/Users/fau/go/src/github.com/gorilla/sessions (from $GOPATH)
/Users/fau/go/src/gowa/lib/MultiVariableLRpage.go:4:2: cannot find package "mkcog/mkcog/lib" in any of:
	/usr/local/go/src/mkcog/mkcog/lib (from $GOROOT)
	/Users/fau/go/src/mkcog/mkcog/lib (from $GOPATH) (exit status 1)

¿Como obtengo la dependencia de kcog/mkcog/lib ?

¿Existe alguna forma donde el proyecto descargue las dependencias en automatico?

**Comment by camachojua** [comment]
Mmm ese error trata de abrir una biblioteca de la máquina cognita que nos mostró el Dr. ¿Sabes cuál es el ejemplo en concreto que quieres correr?

**Comment by ffmorales** [comment]
> Mmm ese error trata de abrir una biblioteca de la máquina cognita que nos mostró el Dr. ¿Sabes cuál es el ejemplo en concreto que quieres correr?

El ejemplo es el código de gowa:
https://github.com/camachojua/diplomado-ia/blob/main/go/src/gowa.zip

Pero no sé cómo obtener las dependencias.

**Comment by camachojua** [comment]
Más bien, `gowa` es una colección de programas, no va a correr con tan solo descomprimirlo ya que no he confirmado el estado de la aplicación al momento en el que el Dr. nos compartió el archivo ¿Qué estás ejecutando en el `main`?

**Comment by ffmorales** [comment]
> Más bien, `gowa` es una colección de programas, no va a correr con tan solo descomprimirlo ya que no he confirmado el estado de la aplicación al momento en el que el Dr. nos compartió el archivo ¿Qué estás ejecutando en el `main`?

Descomprimí el archivo gowa.zip. Leí el README.md e indica correr el archivo gowamain.go en el cmd de la ruta: .../gowa/cmd/gowamain.go

**Comment by camachojua** [comment]
Ya, en el archimo `go.mod` tenemos la siguiente definicion:

```go
require mkcog/mkcog v0.0.0

replace mkcog/mkcog => /drv3/hm3/code/go/src/mkcog
```

Lo cual busca la carpeta `/drv3/hm3/code/go/src/mkcog` por lo tanto el Dr. Compartió el código pero existirán llamadas a `mkcog` que tenemos que desarrollar por nuestra cuenta.

**Comment by ffmorales** [comment]
Como complemento.

He visto como descargar dependencias en automático.
Para ello, use los siguientes comandos:

- echo "export GO111MODULE=on" >> ~/.bash_profile
- source ~/.bash_profile
- cd "ruta de gowa"
- go mod tidy

https://blog.friendsofgo.tech/posts/go-modules-en-tres-pasos/

Con esos comandos empezó a realizar la descarga de dependencias.

Donde la terminal indico que todo ok, hasta el faltante de mkcog:
go: downloading github.com/gorilla/sessions v1.3.0
go: downloading github.com/go-sql-driver/mysql v1.8.1
go: downloading github.com/gorilla/securecookie v1.1.2
go: downloading filippo.io/edwards25519 v1.1.0
go: gowa/lib imports
	mkcog/mkcog/lib: mkcog/mkcog@v0.0.0: replacement directory /drv3/hm3/code/go/src/mkcog does not exist
go: gowa/lib imports
	github.com/gorilla/sessions imports
	github.com/gorilla/securecookie tested by
	github.com/gorilla/securecookie.test imports
	github.com/google/gofuzz: mkcog/mkcog@v0.0.0 (replaced by /drv3/hm3/code/go/src/mkcog): reading /drv3/hm3/code/go/src/mkcog/go.mod: open /drv3/hm3/code/go/src/mkcog/go.mod: no such file or directory

Debido a que mkcog es justo el código de maquina cógnica que el profesor no va a brindar. No permite su ejecución. Sin embargo, su módulo ya tiene una nomenclatura y al no tenerlo hace complicada la integración de nuevo código.
