### ISSUE TITLE
Error al ejecutar codigo ejemplo de clase

### ISSUE THREAD

**Issue by jmc-ops** [camachojua/diplomado-ia#3]
Hola. 
A mi se me presento el siguiente problema al tratar de ejecutar el siguiente codigo desde VSCode que tengo conectado con WSL .
Nota: No tuve ningun problema en la instalación de go y linux 

Hay que hacer algo adicional para que corra el codigo ?

![Screenshot 2024-08-16 172637](https://github.com/user-attachments/assets/3cda6964-3421-4b8d-89e6-de8443e842f9)

package main

import "fmt"

func val1() bool {
	package main

import "fmt"

func val1() bool {
	fmt.Println("val1 gets called")
	return true
}
func val2() bool {
	fmt.Println("val2 gets called")
	return false
}
func main() {
	if val1() && val2() {
		fmt.Println("Shouldn't print")
	}
	fmt.Println("Testing for the second time")
	if val2() && val1() {
		fmt.Println("Shouldn't print")
	}
	if val1() || val2() {
		fmt.Println("The boolean expression is true")
	}
	if val2() || val1() {
		fmt.Println("The boolean expression is true")
	}
}fmt.Println("val1 gets called")
	return true
}
func val2() bool {
	fmt.Println("val2 gets called")
	return false
}
func main() {
	if val1() && val2() {
		fmt.Println("Shouldn't print")
	}
	fmt.Println("Testing for the second time")
	if val2() && val1() {
		fmt.Println("Shouldn't print")
	}
	if val1() || val2() {
		fmt.Println("The boolean expression is true")
	}
	if val2() || val1() {
		fmt.Println("The boolean expression is true")
	}
}

**Comment by camachojua** [comment]
Hola @jmc-ops ¿Podrías compartir el contenido `/home/jmcarpio/go/bin/dlv` ? El error dice que falta un archivo llamado `go.mod`

¿Ejecutaste el comando `go mod init` ?

**Comment by ivanjpg** [comment]
@jmc-ops puedes insertar bloques de código dentro de los issues en Github, en el editor tienes un iconito así: _<>_. Con eso es más fácil seguir tu código. También tienes repetidos demasiados pedazos de código, aguas al pegarlo. 

Para visualizar cómo veremos los demás tu mensaje, da click en _Preview_.

**Comment by camachojua** [comment]
@jmc-ops Otra cuestión, la función `main` está declarada dos veces en el código que pegaste

**Comment by jmc-ops** [comment]
Les comparto lo que visualizo en la consola
![Screenshot 2024-08-16 1742](https://github.com/user-attachments/assets/7f65b560-d879-42e7-b013-deb71bfda6b0)

**Comment by ivanjpg** [comment]
Te completo por acá el ejemplo con el bloque de código correcto:

```go
package main

import "fmt"

func val1() bool {
	fmt.Println("val1 gets called")
	return true
}

func val2() bool {
	fmt.Println("val2 gets called")
	return false
}

func main() {
	if val1() && val2() {
		fmt.Println("Shouldn't print")
	}

	fmt.Println("Testing for the second time")

	if val2() && val1() {
		fmt.Println("Shouldn't print")
	}

	if val1() || val2() {
		fmt.Println("The boolean expression is true")
	}

	if val2() || val1() {
		fmt.Println("The boolean expression is true")
	}
}
```
Tienes dos opciones para correrlo, la primera es directamente:
- Para ejecutarlo directamente puedes usar:  `go run tuarchivo.go`

La segunda es usar el toolchain de go para construirlo a manera de _módulo_. Para ello ejecutas
- `go mod init ejemplo01` esto genera un archivo `go.mod` con la información básica como el nombre del módulo y la versión de go.
- Ejecutas `go build` lo que genera un archivo llamado `ejemplo01` que es ejecutable.
- Corres tu programa ejecutable: `./ejemplo01` 

¡Suerte! :four_leaf_clover:

**Comment by ivanjpg** [comment]
> Les comparto lo que visualizo en la consola ![Screenshot 2024-08-16 1742](https://private-user-images.githubusercontent.com/178619329/358767778-7f65b560-d879-42e7-b013-deb71bfda6b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTIwNTksIm5iZiI6MTcyMzg1MTc1OSwicGF0aCI6Ii8xNzg2MTkzMjkvMzU4NzY3Nzc4LTdmNjViNTYwLWQ4NzktNDJlNy1iMDEzLWRlYjcxYmZkYTZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQyMzQyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDY1YjBjZDMyMjVkN2NhOTJjMjVkMTY4OWExYWIxYzA1YjU5ZDBlZWEwMDA1OGRmNDdiOGFlZDAzM2I0OGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oLTBjrY98N2QnRQbmu2L_1rGzeTkCCWjEd82WWFzHFQ)

`go mod init` no es una instrucción de go, es un comando para ejecutar en una terminal. Además, trata de no usar espacios en los nombres de archivos.

**Comment by camachojua** [comment]
@jmc-ops Es importante que dentro de la carpeta donde está el archivo `package main.go 1` tengas un archivo llamado `go.mod`

Edit: Si te sirve este podría ser el contenido del archivo:

```go
module nombre

go 1.22.6
```

Donde `nombre` sería el nombre de la carpeta donde tienes el código, por ejemplo

**Comment by FelipeAlvarezZuloaga** [comment]
en su momento a mi me sirvió crear un archivo .txt, en el directorio donde voy a poner mis archivos, y luego le cambié el nombre a go.mod con el contenido siguiente: 

module nombre_del_directorio

go 1.22.4

**Comment by camachojua** [comment]
@jmc-ops ¿Pudiste ejecutar el código?

**Comment by camachojua** [comment]
Se cierra el issue por falta de respuesta del interesado
