### ISSUE TITLE
Reorganización de directorios

### ISSUE THREAD

**Issue by ivanjpg** [camachojua/diplomado-ia#30]
No existen directorios predefinidos para los envíos de los alumnos. Por ello, se propone reorganizar los directorios dentro de la carpeta `student_submissions` . Además de añadir los archivos parquet, csv y temporales de Mac a `.gitignore`.

**Comment by camachojua** [comment]
¿Puedes hacer de nuevo el rebase? No ví que habías actualizado tu PR hace tiempo
