### ISSUE TITLE
Problemas con instalación Linux/go/VSC

### ISSUE THREAD

**Issue by RicardoMossoGuerrero** [camachojua/diplomado-ia#4]
Tengo Widows, primero instale wsl2 y posteriormente linux esta es la versión que tengo su puestamente  

![Captura de pantalla 2024-08-16 185732](https://github.com/user-attachments/assets/89e554d3-cdb3-48c4-ab96-df22fd93abe6)

al momento de entrar el VSC e intentar abrir un archivo en GO, me aparce esto 

![image](https://github.com/user-attachments/assets/1149a93c-6591-4220-a0d4-dbd4ed441645)

Disculpen si mi error es muy tonto, pero nunca he usado linux anteriormente, ¿alguien podría apoyarme? 

Saludos.

**Comment by camachojua** [comment]
Hola @RicardoMossoGuerrero te faltó conectar tu VSCode con tu WSL ¿Podrías completar el [tutorial](https://learn.microsoft.com/en-us/training/modules/developing-in-wsl/?source=recommendations) que viene ligado en el `README.md` del proyecto?

Edit: Debes instalar esta [extensión](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) de VSCode

**Comment by camachojua** [comment]
@RicardoMossoGuerrero ¿Pudiste ejecutar tu código?

**Comment by camachojua** [comment]
Se cierra el issue por falta de respuesta del interesado
